spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: AB_JMX_EXPORTER_CONFIG
            value: "prometheus.yml"