spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: 0.2
              memory: 128Mi
            limits:
              cpu: 2.0
              memory: 512Mi
          # env:
          # - name: AB_JMX_EXPORTER_CONFIG
          #   value: "prometheus.yml"