apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: secure-topic-writer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example Producer Acls for topic lines
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
        host: "*"